export default {
  CHROME_BOTTOM: '.ytp-chrome-bottom',
  GRADIANT_BOTTOM: '.ytp-gradient-bottom',
  NEXT_BUTTON: '.ytp-search-next-btn',
  PLAY_PROGRESS: '.ytp-play-progress',
  PREV_BUTTON: '.ytp-search-prev-btn',
  PREVIEW: '.ytp-preview',
  RIGHT_CONTROLS: '.ytp-right-controls',
  SEARCH_BUTTON: '.ytp-search-button',
  SEARCH_INPUT: '.ytp-search-left-wrapper input',
  SEARCH_MENU: '.ytp-search-menu',
  SEARCH_RESULTS: '.ytp-search-results',
  SEARCH_LEFT_WRAPPER: '.ytp-search-left-wrapper',
  SEARCH_RIGHT_WRAPPER: '.ytp-search-right-wrapper',
  SETTINGS_MENU: '.ytp-settings-menu',
  SUBTITLES_BUTTON: '.ytp-subtitles-button',
  SUBTITLES_ICON: '.ytp-subtitles-button-icon',
  TIME_CURRENT: '.ytp-time-current',
  TOOLTIP: '.ytp-tooltip',
  TOOLTIP_BG: '.ytp-tooltip-bg',
  TOOLTIP_TEXT: '.ytp-tooltip-text',
  TOOLTIP_TEXT_WRAPPER: '.ytp-tooltip-text-wrapper',
  TRANSCRIPT: 'ytd-engagement-panel-section-list-renderer[target-id=\'engagement-panel-searchable-transcript\'],ytd-engagement-panel-section-list-renderer[target-id=\'engagement-panel-transcript\']',
  TRANSCRIPT_LIST: 'ytd-transcript-segment-list-renderer,ytd-transcript-body-renderer',
  TRANSCRIPT_RENDERER: 'ytd-transcript-renderer',
  TRANSCRIPT_ITEM: 'ytd-transcript-segment-renderer,.cue-group',
  TRANSCRIPT_TEXT: '.segment-text,.cue',
  TRANSCRIPT_TIMESTAMP: '.segment-timestamp,.cue-group-start-offset',
  VIDEO: 'video',
  VIDEO_PLAYER: '.html5-video-player',
};
