export default {
  CHROME_BOTTOM: 'ytd-watch-flexy .ytp-chrome-bottom',
  GRADIANT_BOTTOM: 'ytd-watch-flexy .ytp-gradient-bottom',
  IV_PLAYER_CONTENT: 'ytd-watch-flexy .ytp-iv-player-content',
  IV_VIDEO_CONTENT: 'ytd-watch-flexy .ytp-iv-video-content',
  NEXT_BUTTON: 'ytd-watch-flexy .ytp-search-next-btn',
  PLAY_PROGRESS: 'ytd-watch-flexy .ytp-play-progress',
  PLAYER_CONTENT: 'ytd-watch-flexy .ytp-player-content',
  PREV_BUTTON: 'ytd-watch-flexy .ytp-search-prev-btn',
  PREVIEW: 'ytd-watch-flexy .ytp-preview',
  RIGHT_CONTROLS: 'ytd-watch-flexy .ytp-right-controls',
  SEARCH_BUTTON: 'ytd-watch-flexy .ytp-search-button',
  SEARCH_INPUT: 'ytd-watch-flexy .ytp-search-left-wrapper input',
  SEARCH_MENU: 'ytd-watch-flexy .ytp-search-menu',
  SEARCH_RESULTS: 'ytd-watch-flexy .ytp-search-results',
  SEARCH_LEFT_WRAPPER: 'ytd-watch-flexy .ytp-search-left-wrapper',
  SEARCH_RIGHT_WRAPPER: 'ytd-watch-flexy .ytp-search-right-wrapper',
  SETTINGS_MENU: 'ytd-watch-flexy .ytp-settings-menu',
  SUBTITLES_BUTTON: 'ytd-watch-flexy .ytp-subtitles-button',
  SUBTITLES_ICON: 'ytd-watch-flexy .ytp-subtitles-button-icon',
  TIME_CURRENT: 'ytd-watch-flexy .ytp-time-current',
  TOOLTIP: 'ytd-watch-flexy .ytp-tooltip',
  TOOLTIP_BG: 'ytd-watch-flexy .ytp-tooltip-bg',
  TOOLTIP_TITLE: 'ytd-watch-flex .ytp-tooltip-title',
  TOOLTIP_TEXT: 'ytd-watch-flexy .ytp-tooltip-text',
  TOOLTIP_TEXT_WRAPPER: 'ytd-watch-flexy .ytp-tooltip-text-wrapper',
  TRANSCRIPT: 'ytd-engagement-panel-section-list-renderer[target-id=\'engagement-panel-searchable-transcript\'],ytd-engagement-panel-section-list-renderer[target-id=\'engagement-panel-transcript\']',
  TRANSCRIPT_LIST: 'ytd-transcript-segment-list-renderer,ytd-transcript-body-renderer',
  TRANSCRIPT_RENDERER: 'ytd-transcript-renderer',
  TRANSCRIPT_ITEM: 'ytd-transcript-segment-renderer,.cue-group',
  TRANSCRIPT_TEXT: '.segment-text,.cue',
  TRANSCRIPT_TIMESTAMP: '.segment-timestamp,.cue-group-start-offset',
  VIDEO: 'ytd-watch-flexy video',
  VIDEO_PLAYER: 'ytd-watch-flexy .html5-video-player',
};
